version: '3.8'

services:
  postgres:
    image: postgres:${POSTGRES_VERSION}
    container_name: ${POSTGRES_CONTAINER_NAME}
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '${POSTGRES_PORT}:5432'
    volumes:
      - financeflow_pgdata:/var/lib/postgresql/data
    networks:
      - financeflow_network

volumes:
  financeflow_pgdata:

networks:
  financeflow_network:
    driver: bridge
